### ISSUE TITLE
运行微调代码报错

### ISSUE THREAD

**Issue by KekeWa** [wangyuxinwhy/uniem#10]
<img width="1331" alt="image" src="https://github.com/wangyuxinwhy/uniem/assets/37018609/1830eb55-ab28-461d-9fc5-bf10c22376f0">
如图所示，符号异常是为啥呢? 我查阅资料发现，match语法python3.7不支持，您是python3.10吗？感觉可以把版本号也顺带澄清一下

**Comment by wangyuxinwhy** [comment]
match 语法和 type hints 的部分语法都是需要 Python 3.10 版本才行。在 README 中的环境准备中有标明需要 python=3.10 ，如下所示。

```bash
conda create -n uniem python=3.10
```

不过可能不够明显，所以您没有注意到，我会在 README 添加 badges 来更显著的说明
