### ISSUE TITLE
单句分类的微调

### ISSUE THREAD

**Issue by bulululu** [wangyuxinwhy/uniem#103]
### 🚀 The feature

小白提问：在微调支持的数据类型里没有找到单句分类的数据类型，是不支持吗？还是可以实现呢？具体实现的思路应该是怎样的？

**Comment by wangyuxinwhy** [comment]
m3e 模型是 embdding 模型，不是句子分类的模型，所以不支持句子分类任务的微调。可以尝试使用原始的  bert 模型来完成分类任务
