### ISSUE TITLE
实际测试 PairInBatchNegSoftmaxContrastLoss和PairInBatchNegCoSentLoss的值是一样的

### ISSUE THREAD

**Issue by WEN6Lev57q4** [wangyuxinwhy/uniem#121]
### 🐛 bug 说明

text_embedding = torch.ones((2,3)).float()
text_pos_embedding = torch.ones((2,3)).float()

cosent_l = PairInBatchNegCoSentLoss()
print(cosent_l(text_embedding,text_pos_embedding))

softmax_l = PairInBatchNegSoftmaxContrastLoss()
print(softmax_l(text_embedding, text_pos_embedding)) 跑出的结果一致

### Python Version

None

**Comment by wangyuxinwhy** [comment]
你这个 case 可能计算结果是一样的，测测实际中的例子，就会发现两者不同。
