### ISSUE TITLE
问下怎么切换s2s、s2p、s2c

### ISSUE THREAD

**Issue by TccccD** [wangyuxinwhy/uniem#2]
很棒的工作！我目前正在做检索任务，问下怎么切换s2s、s2p，目前貌似只有一个encode方法，我直接embe_q=model.encode(问题) 和 embe_p=model.encode(文档)，embe_q和embe_p做相似度对比吗。

**Comment by wangyuxinwhy** [comment]
是的，直接这么用就可以了，不需要其他的操作。因为 M3E 模型的训练集中包括千万级的 S2P 检索对。

**Comment by TccccD** [comment]
> 是的，直接这么用就可以了，不需要其他的操作。因为 M3E 模型的训练集中包括千万级的 S2P 检索对。

好的 感谢！
