### ISSUE TITLE
目前的训练脚本是否支持多卡呢?

### ISSUE THREAD

**Issue by hjq133** [wangyuxinwhy/uniem#21]
看上去目前的finetune和train脚本都是基于单卡的脚本。

**Comment by wangyuxinwhy** [comment]
由于训练代码是基于 accelerate 实现的，所以 accelerate 支持的训练方案都可以支持。单机多卡，多机多卡都可以，还有 DeepSpeed,FSDDP,TPU 等

**Comment by hjq133** [comment]
感谢回复，了解了！
