### ISSUE TITLE
process_zh_datasets.py load_wiki_atomic_edits 

### ISSUE THREAD

**Issue by hjq133** [wangyuxinwhy/uniem#25]
### 🐛 bug 说明

load_wiki_atomic_edits的原始process函数如下
 
   def _process(example):
        return {
            'base_sentence': concat_words(example['base_sentence'].split(' ')),
            'edited_sentence': concat_words(example['edited_sentence'].split(' ')),
        }

return 的key应该是'text'和'text_pos'，而不是'base_sentence'和'edited_sentence'
这里应该写错了。

### Python Version

None

**Comment by wangyuxinwhy** [comment]
感谢指正，已经修复了。之前在本地修改了，忘记更新了...
