### ISSUE TITLE
mean pooling 与 embedding_strategy 问题

### ISSUE THREAD

**Issue by Sdamuu** [wangyuxinwhy/uniem#3]
辛苦问个问题，使用 sentence-transformers 进行 encode 时最后会加上一个 mean pooling 操作，然后将池化后的特征作为最终的特征，model 定义时候我看可选cls, last_mean, first_last_mean,embedding_last_mean, last_weighted 几种不同的方式，这个的选择对最终embedding 效果有影响吗？

**Comment by wangyuxinwhy** [comment]
抱歉，这么晚回复您。cls, last_mean, first_last_mean,embedding_last_mean, last_weighted 这些都是我们在训练模型时，用作实验的 Polling 策略，最终我们发现  last_mean 确实是在 In-Batch 对比学习中表现更好更稳定的策略。这恰好是 sentence-transformers 的默认选择，所以如果使用 uniem 进行模型训练时，选择 last_mean 作为 Polling 策略，可以在不做任何修改的情况下，无缝衔接 sentence-transformers，如果选择其他策略，可能需要进行一些修改。
