### ISSUE TITLE
复现M3E-Base

### ISSUE THREAD

**Issue by hjq133** [wangyuxinwhy/uniem#35]
如果想要复现M3E-Base的结果，不知道作者方便透露下具体的参数或者相应的config file吗，
还是说train_m3e.py里的默认参数已经是最优参数了？
感谢！

**Comment by wangyuxinwhy** [comment]
temperature=0.01
batch_size=80
epochs=1
mixed_precision=fp16
其他都是默认的参数

**Comment by hjq133** [comment]
感谢!

**Comment by gaoxiao** [comment]
> 

请问训练数据集方便share吗?

**Comment by wangyuxinwhy** [comment]
> > 
> 
> 请问训练数据集方便share吗?

https://huggingface.co/moka-ai/m3e-base#%F0%9F%93%82-m3e%E6%95%B0%E6%8D%AE%E9%9B%86 

可以查看这个链接
