### ISSUE TITLE
关于评测测试集

### ISSUE THREAD

**Issue by Nipi64310** [wangyuxinwhy/uniem#38]
### 🚀 The feature

Hi @wangyuxinwhy ,
请问mteb-zh评测测试集为什么跟text2vec测试集不同？是因为m3e训练数据大部分都是qa形式吗，短q长a，而相似度数据偏向于较短的qq pair吗

比如这几个测试集 https://github.com/bojone/BERT-whitening/tree/main/chn
![image](https://github.com/wangyuxinwhy/uniem/assets/31469418/ba7b9864-ded7-43c6-9a70-bdef612b18d3)

**Comment by Nipi64310** [comment]
另外关于T2RankingRetrieval的测试结果，波动也挺大的
前1w
```
{
  "dataset_revision": null,
  "dev": {
    "evaluation_time": 58.32,
    "map_at_1": 0.62604,
    "map_at_10": 0.76562,
    "map_at_100": 0.76935,
    "map_at_1000": 0.76946,
    "map_at_3": 0.74276,
    "map_at_5": 0.75673,
    "mrr_at_1": 0.70472,
    "mrr_at_10": 0.78407,
    "mrr_at_100": 0.78648,
    "mrr_at_1000": 0.78656,
    "mrr_at_3": 0.77296,
    "mrr_at_5": 0.77937,
    "ndcg_at_1": 0.68812,
    "ndcg_at_10": 0.80044,
    "ndcg_at_100": 0.81481,
    "ndcg_at_1000": 0.81749,
    "ndcg_at_3": 0.76875,
    "ndcg_at_5": 0.7854,
    "precision_at_1": 0.70472,
    "precision_at_10": 0.11404,
    "precision_at_100": 0.01228,
    "precision_at_1000": 0.00125,
    "precision_at_3": 0.33378,
    "precision_at_5": 0.21409,
    "recall_at_1": 0.62604,
    "recall_at_10": 0.90152,
    "recall_at_100": 0.96435,
    "recall_at_1000": 0.9852,
    "recall_at_3": 0.81921,
    "recall_at_5": 0.8585
  },
  "mteb_dataset_name": "T2RankingRetrieval",
  "mteb_version": "1.0.2"
}
```
取前50000个，指定T2RRetrieval(50000) 之后
```
{
  "dataset_revision": null,
  "dev": {
    "evaluation_time": 274.28,
    "map_at_1": 0.4685,
    "map_at_10": 0.64094,
    "map_at_100": 0.64823,
    "map_at_1000": 0.64852,
    "map_at_3": 0.60373,
    "map_at_5": 0.62774,
    "mrr_at_1": 0.58691,
    "mrr_at_10": 0.68553,
    "mrr_at_100": 0.68949,
    "mrr_at_1000": 0.68965,
    "mrr_at_3": 0.66791,
    "mrr_at_5": 0.6794,
    "ndcg_at_1": 0.56037,
    "ndcg_at_10": 0.69202,
    "ndcg_at_100": 0.71822,
    "ndcg_at_1000": 0.72416,
    "ndcg_at_3": 0.64188,
    "ndcg_at_5": 0.67009,
    "precision_at_1": 0.58697,
    "precision_at_10": 0.11869,
    "precision_at_100": 0.01364,
    "precision_at_1000": 0.00143,
    "precision_at_3": 0.31867,
    "precision_at_5": 0.21531,
    "recall_at_1": 0.4685,
    "recall_at_10": 0.82275,
    "recall_at_100": 0.93552,
    "recall_at_1000": 0.97949,
    "recall_at_3": 0.69302,
    "recall_at_5": 0.76062
  },
  "mteb_dataset_name": "T2RankingRetrieval",
  "mteb_version": "1.0.2"
}
```

**Comment by hjq133** [comment]
我看M3E把BQ、LCQMC、PAWSX的测试集也加进去训练了。比较那几个不一定公平。

**Comment by Nipi64310** [comment]
> 我看M3E把BQ、LCQMC、PAWSX的测试集也加进去训练了。比较那几个不一定公平。

Hello @hjq133 ,
但是实际测试，m3e-base在这几个测试集上效果都比较差。。
测试脚本如下，修改于 https://github.com/bojone/BERT-whitening/tree/main/chn
```
from datasets import load_dataset

dataset = load_dataset("shibing624/nli_zh", "BQ") # ATEC or BQ or LCQMC or PAWSX or STS-B
print(dataset)
print(dataset['test'][:2])
import numpy as np
import scipy.stats
from sentence_transformers import SentenceTransformer
model_path = 'moka-ai/m3e-base'
model = SentenceTransformer(model_path,device='cuda')
def convert_to_vecs(data):
    """转换文本数据为向量形式
    """
    a_vecs = model.encode(data['sentence1'],batch_size=32)
    b_vecs = model.encode(data['sentence2'],batch_size=32)
    return a_vecs, b_vecs, np.array(data['label'])
a_vecs, b_vecs,labels = convert_to_vecs(dataset['test'])


def transform_and_normalize(vecs, kernel=None, bias=None):
    """应用变换，然后标准化
    """
    if not (kernel is None or bias is None):
        vecs = (vecs + bias).dot(kernel)
    norms = (vecs**2).sum(axis=1, keepdims=True)**0.5
    return vecs / np.clip(norms, 1e-8, np.inf)

def compute_corrcoef(x, y):
    """Spearman相关系数
    """
    return scipy.stats.spearmanr(x, y).correlation

# 变换，标准化，相似度，相关系数
all_corrcoefs = []
a_vecs = transform_and_normalize(a_vecs)
b_vecs = transform_and_normalize(b_vecs)
sims = (a_vecs * b_vecs).sum(axis=1)
corrcoef = compute_corrcoef(labels, sims)
all_corrcoefs.append(corrcoef)
print(all_corrcoefs)

# [0.6381030399066687]
```

![image](https://github.com/wangyuxinwhy/uniem/assets/31469418/9ced9834-2435-423f-97a9-6285d0dbb980)

**Comment by wangyuxinwhy** [comment]
![](https://yuxin-wang.oss-cn-beijing.aliyuncs.com/uPic/jbbNfT.png)

这个是我看之前 text2vec 的评测结果

至于为什么没有使用 text2vec 的评测集，主要有两个考虑
1. 对比不公平，text2vec 使用了数据集中的正例和负例，M3E 只使用了这些数据集中的正例，没有使用这些数据集中的负例，但可能因为划分方式的问题，导致标签泄漏。
2. 用户实际使用中肯定都是域外的数据集，从公平和实用的角度，我选择了 text2vec 和 m3e 都没有见过的数据集，尽量保证这些数据集的领域和任务都不同。

> 比如，上面图片中的 SOHU 数据集，text2vec 是在这个数据集上训练的，而 M3E 是从来没有见过这个数据集的，因此这样的比较肯定是有问题的，所以 text2vec 的作者在新的 README 中删掉了这一行。

**Comment by hjq133** [comment]
> > 我看M3E把BQ、LCQMC、PAWSX的测试集也加进去训练了。比较那几个不一定公平。
> 
> Hello @hjq133 , 但是实际测试，m3e-base在这几个测试集上效果都比较差。。 测试脚本如下，修改于 https://github.com/bojone/BERT-whitening/tree/main/chn
> 
> ```
> from datasets import load_dataset
> 
> dataset = load_dataset("shibing624/nli_zh", "BQ") # ATEC or BQ or LCQMC or PAWSX or STS-B
> print(dataset)
> print(dataset['test'][:2])
> import numpy as np
> import scipy.stats
> from sentence_transformers import SentenceTransformer
> model_path = 'moka-ai/m3e-base'
> model = SentenceTransformer(model_path,device='cuda')
> def convert_to_vecs(data):
>     """转换文本数据为向量形式
>     """
>     a_vecs = model.encode(data['sentence1'],batch_size=32)
>     b_vecs = model.encode(data['sentence2'],batch_size=32)
>     return a_vecs, b_vecs, np.array(data['label'])
> a_vecs, b_vecs,labels = convert_to_vecs(dataset['test'])
> 
> 
> def transform_and_normalize(vecs, kernel=None, bias=None):
>     """应用变换，然后标准化
>     """
>     if not (kernel is None or bias is None):
>         vecs = (vecs + bias).dot(kernel)
>     norms = (vecs**2).sum(axis=1, keepdims=True)**0.5
>     return vecs / np.clip(norms, 1e-8, np.inf)
> 
> def compute_corrcoef(x, y):
>     """Spearman相关系数
>     """
>     return scipy.stats.spearmanr(x, y).correlation
> 
> # 变换，标准化，相似度，相关系数
> all_corrcoefs = []
> a_vecs = transform_and_normalize(a_vecs)
> b_vecs = transform_and_normalize(b_vecs)
> sims = (a_vecs * b_vecs).sum(axis=1)
> corrcoef = compute_corrcoef(labels, sims)
> all_corrcoefs.append(corrcoef)
> print(all_corrcoefs)
> 
> # [0.6381030399066687]
> ```
> 
> ![image](https://user-images.githubusercontent.com/31469418/252261922-9ced9834-2435-423f-97a9-6285d0dbb980.png)

你这比较不太对。他那个是拿pretrain单独在每个集子上单独finetune的结果、
所以你得拿M3E单独每个集子train后再去测试。
https://github.com/shibing624/text2vec/issues/51

**Comment by wangyuxinwhy** [comment]
> > > 我看M3E把BQ、LCQMC、PAWSX的测试集也加进去训练了。比较那几个不一定公平。
> > 
> > 
> > Hello @hjq133 , 但是实际测试，m3e-base在这几个测试集上效果都比较差。。 测试脚本如下，修改于 https://github.com/bojone/BERT-whitening/tree/main/chn
> > ```
> > from datasets import load_dataset
> > 
> > dataset = load_dataset("shibing624/nli_zh", "BQ") # ATEC or BQ or LCQMC or PAWSX or STS-B
> > print(dataset)
> > print(dataset['test'][:2])
> > import numpy as np
> > import scipy.stats
> > from sentence_transformers import SentenceTransformer
> > model_path = 'moka-ai/m3e-base'
> > model = SentenceTransformer(model_path,device='cuda')
> > def convert_to_vecs(data):
> >     """转换文本数据为向量形式
> >     """
> >     a_vecs = model.encode(data['sentence1'],batch_size=32)
> >     b_vecs = model.encode(data['sentence2'],batch_size=32)
> >     return a_vecs, b_vecs, np.array(data['label'])
> > a_vecs, b_vecs,labels = convert_to_vecs(dataset['test'])
> > 
> > 
> > def transform_and_normalize(vecs, kernel=None, bias=None):
> >     """应用变换，然后标准化
> >     """
> >     if not (kernel is None or bias is None):
> >         vecs = (vecs + bias).dot(kernel)
> >     norms = (vecs**2).sum(axis=1, keepdims=True)**0.5
> >     return vecs / np.clip(norms, 1e-8, np.inf)
> > 
> > def compute_corrcoef(x, y):
> >     """Spearman相关系数
> >     """
> >     return scipy.stats.spearmanr(x, y).correlation
> > 
> > # 变换，标准化，相似度，相关系数
> > all_corrcoefs = []
> > a_vecs = transform_and_normalize(a_vecs)
> > b_vecs = transform_and_normalize(b_vecs)
> > sims = (a_vecs * b_vecs).sum(axis=1)
> > corrcoef = compute_corrcoef(labels, sims)
> > all_corrcoefs.append(corrcoef)
> > print(all_corrcoefs)
> > 
> > # [0.6381030399066687]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/31469418/252261922-9ced9834-2435-423f-97a9-6285d0dbb980.png)
> 
> 你这比较不太对。他那个是拿pretrain单独在每个集子上单独finetune的结果、 所以你得拿M3E单独每个集子train后再去测试。 [shibing624/text2vec#51](https://github.com/shibing624/text2vec/issues/51)

对的，应该看我上面回复的那张图，其实 M3E 我觉得表现的并不差，和 text2vec 的水平差不多。另外，如果是想要看那个模型更适合你，不如直接在自己的场景上面测试~

**Comment by Nipi64310** [comment]
感谢回复
