### ISSUE TITLE
typo in source code

### ISSUE THREAD

**Issue by habaneraa** [wangyuxinwhy/uniem#44]
https://github.com/wangyuxinwhy/uniem/blob/4062a0b3ae18f3e1fe56e125a702cb2f98a1b0d7/uniem/integration/sentence_transformers_wrapper.py#L32

在 PyPI 中这个包的名字是 `sentence-transformers`. 所以需要改成 `pip install sentence-transformers` ~

**Comment by wangyuxinwhy** [comment]
哈哈，好的，好像 pip install 的时候会自动把 **_** 转换成 **-**，所以真运行这个也没有问题。

你如果愿意提一个 PR ，我可以直接合并。如果你觉得麻烦的话，我会在下一次发布的时候修复这个 typo

**Comment by habaneraa** [comment]
> 哈哈，好的，好像 pip install 的时候会自动把 **_** 转换成 **-**，所以真运行这个也没有问题。

你说得对，所以不用改了，见 [这个](https://packaging.python.org/en/latest/specifications/name-normalization/)
