### ISSUE TITLE
max_length 和 position embedding 相关

### ISSUE THREAD

**Issue by hjq133** [wangyuxinwhy/uniem#50]
![2023-07-13 21-09-44屏幕截图](https://github.com/wangyuxinwhy/uniem/assets/37239015/0e24db4e-a50a-4d86-8079-266b817486af)

在看E5论文的时候发现，他们在pretrain和finetune时分别采用了128和192的max length，同时fix住了position embedding，
因此测试时也能把length设置为最大的512。
我猜测这样的优势是训练速度会比较快？不知道M3E有没有做过相关的尝试，比如fix住pos embedding而采用较小的max_length以加快训练速度，不知道对精度的影响如何。

**Comment by hjq133** [comment]
感谢回复，刚好想说，随之而来的另一个问题就是，观察到M3E的训练集里，有很多的token长度超过512的文本，甚至有些文本在2000以上，是不是需要在预处理时，把过长的（比如超过某个thresh 的）文本给去掉。这样至少保证tokenizer在进行truncate时，不会丢失太多语义。

**Comment by wangyuxinwhy** [comment]
是的，这样处理起来会更精细一些，但不一定有显著的差异。考虑到文本摘要有 lead-3 （选前三句话作为摘要，开门见山~） 作为 baseline 的传统，我们可以假定前 512 个字作为监督信号也是有可取之处的。
