### ISSUE TITLE
onnx支持

### ISSUE THREAD

**Issue by tomjamescn** [wangyuxinwhy/uniem#51]
### 🚀 The feature

能否支持onnx

**Comment by wangyuxinwhy** [comment]
m3e 没有特殊结构和算子，可以使用 optimum 中的 [ORTModelForFeatureExtraction](https://huggingface.co/docs/optimum/onnxruntime/package_reference/modeling_ort#optimum.onnxruntime.ORTModelForFeatureExtraction) 直接进行转换
