### ISSUE TITLE
T2ranking 取了前1万个doc具体的是怎么理解？

### ISSUE THREAD

**Issue by xjtulixiangyang** [wangyuxinwhy/uniem#54]
### 🐛 bug 说明

是不是就是不丢弃T2ranking dev的那些query和doc pair，获取前1个万个doc之后，然后再将dev里边的doc放进去，然后进行评测是吧？

### Python Version

None

**Comment by wangyuxinwhy** [comment]
就是只取前一万个 doc 以及和这些 doc 相关的 query

**Comment by xjtulixiangyang** [comment]
谢谢啦。
