### ISSUE TITLE
关于T2ranking的评测代码，没有在uniem里边找到。

### ISSUE THREAD

**Issue by xjtulixiangyang** [wangyuxinwhy/uniem#55]
### 🐛 bug 说明

不同于T2ranking自身的评测， 您的文中有引入了 map、MRR、NDCG等指标。方便发一下这个评估的代码，我们这边是防止自己评估的代码与评测代码有微小差异导致评测不准确的问题。

### Python Version

None

**Comment by wangyuxinwhy** [comment]
https://github.com/wangyuxinwhy/uniem/tree/main/mteb-zh

使用的是上面的这个评测工具，可以参考 readme
