### ISSUE TITLE
加载预训练模型的问题，是因为transformer版本问题吗

### ISSUE THREAD

**Issue by KekeWa** [wangyuxinwhy/uniem#57]
### 🐛 bug 说明

用python3.10环境无法加载from_pretrained
<img width="788" alt="image" src="https://github.com/wangyuxinwhy/uniem/assets/37018609/5edac623-8026-49da-af3f-a5e5b4fbdf9d">

### Python Version

3.10

**Comment by wangyuxinwhy** [comment]
```bash
python -m pip install -U uniem 
```

看起来是版本的问题，`from_pretrained` 是 uniem 0.3.0 以上的 api
