### ISSUE TITLE
关于使用accelerate启动多卡的问题

### ISSUE THREAD

**Issue by qianzhang2018** [wangyuxinwhy/uniem#65]
### 🐛 bug 说明

我用指令启动您给的实例脚本  accelerate launch finetune_jsonl.py
然后发现程序报错
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not 
used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to 
`torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` 
function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 197 198
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not 
receive gradient on this rank as part of this error
请教一下您这要怎么解决呀

### Python Version

None

**Comment by qianzhang2018** [comment]
谢谢您的答复和解决方案~
我分别都是尝试了一下这两个方案，好像都有点问题。
方案一：
会直接报错：
ValueError: Expected embedder.encoder.encoder.layer.0 to NOT be FullyShardedDataParallel if using an `auto_wrap_policy`
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 27652 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 27651) of binary: /home/aipf/work/zq_vec/env/bin/python
方案二：
在我更新了您的库后，使用riddle的数据，运行accelerate launch finetune_jsonl.py 能够顺利执行，并且保存了模型。
然后我就把样例数据改成我自己的数据（数据的制造方式和riddle.jsonl相同），但是我的数据比较大。接着用相同的方法去运行，它会先去寻找最合适的batchsize，然后我就看到两张显卡显存都吃满了，但是训练进度条一直没有出现，好像卡死了一样，我再ctrl+c以后，它报了warring。
WARNING:torch.distributed.elastic.agent.server.api:Received 2 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26566 closing signal SIGINT
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26567 closing signal SIGINT
^CWARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26566 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26567 closing signal SIGTERM

**Comment by qianzhang2018** [comment]
方案二在手动指定一个比较小的batsize后就没问题了

**Comment by qianzhang2018** [comment]
第一个方案在小数据集的情况是没问题的。大数据集的情况还是有问题。
问题还是在batch_size上。第一个方案，在我也自己指定batch_size后也仍然就可以了。

最后还是感谢您的开源代码和解决方案~谢谢大佬！

**Comment by wangyuxinwhy** [comment]
好的，感谢反馈

**Comment by windar427** [comment]
使用FSDP finetuner 
TypeError: FineTuner.run() got an unexpected keyword argument 'accelerator_kwargs'

**Comment by wangyuxinwhy** [comment]
> 使用FSDP finetuner TypeError: FineTuner.run() got an unexpected keyword argument 'accelerator_kwargs'

使用 FSDP 的话，可以直接把 accelerator_kwargs 这个参数去掉

**Comment by 1006076811** [comment]
> > 使用FSDP finetuner TypeError: FineTuner.run() got an unexpected keyword argument 'accelerator_kwargs'
> 
> 使用 FSDP 的话，可以直接把 accelerator_kwargs 这个参数去掉

你好，使用第一种方式batch_size设置成8，可以在4个3090成功运行，但是loss一直是Nan，请问可能是什么原因呢。

**Comment by wangyuxinwhy** [comment]
可以先确认一下在非分布式训练的时候，是不是也是 Nan。loss 是 Nan 的情况可能由多种原因导致，需要一步一步 debug ，我的经验也不是很多，所以没有办法给出解决问题的方法。我之前遇到这种情况都是二分法一步一步 debug 的。
