### ISSUE TITLE
请问怎么指定特定的卡来训练

### ISSUE THREAD

**Issue by ericg108** [wangyuxinwhy/uniem#75]
### 🚀 The feature

你好，非常感谢开源这么好用的模型。
想问下，如果在自己的数据集上微调的话，怎么样指定具体的卡来跑呢，
因为我默认0卡上有其他模型，不指定的话会导致0卡OOM，但我用cuda_visible_devices=1,2,3这样设置仍在跑在0卡（汗）
所以，请问有什么办法在指定卡上训练吗，谢谢

**Comment by ucas010** [comment]
类似问题，能不能多卡训练啊？我这有3kw数据需要微调训练，请问有多卡模式么？单卡太慢了。@ @wangyuxinwhy

**Comment by wangyuxinwhy** [comment]
> ### 🚀 The feature
> 你好，非常感谢开源这么好用的模型。 想问下，如果在自己的数据集上微调的话，怎么样指定具体的卡来跑呢， 因为我默认0卡上有其他模型，不指定的话会导致0卡OOM，但我用cuda_visible_devices=1,2,3这样设置仍在跑在0卡（汗） 所以，请问有什么办法在指定卡上训练吗，谢谢

设置环境变量 CUDA_VISIBLE_DEVICES='1,2,3'  这种就可以

**Comment by wangyuxinwhy** [comment]
> 类似问题，能不能多卡训练啊？我这有3kw数据需要微调训练，请问有多卡模式么？单卡太慢了。@ @wangyuxinwhy

可以的，训练脚本是基于 [accelerate](https://huggingface.co/docs/accelerate/index) 实现的，可以参考https://huggingface.co/docs/accelerate/quicktour#launching-your-distributed-script  来进行分布式训练

**Comment by gctian** [comment]
> 

这样配过了，还是会跑在 GPU0上呢，求解

**Comment by gctian** [comment]
不知道为啥会固定跑在 gpu0上，设置环境变量也不管用 @wangyuxinwhy

**Comment by gctian** [comment]
> 那可能还是没有设置对，可以打印环境变量看看有没有正确设置。

设置没问题啊，环境变量设置了，还有代码里也指定了 os.environ，还是报错GPU0 显存不够

**Comment by wangyuxinwhy** [comment]
把报错信息发一下吧，你通过 nvidia-smi 确定模型加载在了 0 卡上，对吗？

**Comment by gctian** [comment]
> 
![image](https://github.com/wangyuxinwhy/uniem/assets/18107813/3391fb2a-e51e-4f2b-b609-c8f7ce4f3f8a)

很奇怪，batch_size过大，运行的时候直接报 GPU:0 显存问题，调小 batch_size运行起来，通过nvidia-smi看，是跑在了指定的卡上，不知道是不是错误收集有问题。。

**Comment by wangyuxinwhy** [comment]
嗯嗯，可能是错误收集有问题。

**Comment by yjdy** [comment]
请问多卡训练的问题有谁解决了吗？我都尝试了，仍然只能在一张卡上训练

**Comment by wangyuxinwhy** [comment]
> 请问多卡训练的问题有谁解决了吗？我都尝试了，仍然只能在一张卡上训练

可以的，训练脚本是基于 [accelerate](https://huggingface.co/docs/accelerate/index) 实现的，可以参考https://huggingface.co/docs/accelerate/quicktour#launching-your-distributed-script 来进行分布式训练。

您是如何实现多卡训练的？
